### ISSUE TITLE
Adding images

### ISSUE THREAD

**Issue by patrickdavey** [dennmart/anki#1]
Hi there,

I haven't played with the gem yet, but is it possible to add image based slides with this gem?  If not, is it a feature you'd be interested in (if I can get the time)

Best,
Patrick

**Comment by dennmart** [comment]
Hey Patrick! As the gem is built now, it's only able to generate strings or files that are plain text only. The cards it can generate are very simple (front, back and tags).

I'd definitely be interested in receiving pull requests for that functionality if you can dig into that. I'll also take a look when I get some spare time at how Anki can import media like images and sounds and see how feasible it is to implement this in this gem.

**Comment by patrickdavey** [comment]
Sounds like a plan.

What I want to do is to create an integration between meetup.com and Anki.  Basically I want to pull in all the members of a group and create flash cards (as I'm awful at remembering names!)  So, I'm not sure how I'll end up doing it.  I was also looking at the APKG format too. http://decks.wikia.com/wiki/Anki_APKG_format_documentation

Anyway, it'll be a while before I'll get round to it, but that's the plan :)

**Comment by benlieb** [comment]
This functionality wouldn't exactly be a snap to implement, but it wouldn't be super hard. 

Anki's allows this: http://ankisrs.net/docs/manual.html#importing-media

The basic idea is you need to add the media files to the anki media directory (which varies by OS), and then in the text string for import, refer to those files: 

```
<img src="myimage.jpg">
[sound:myaudio.mp3]
```

**Comment by patrickdavey** [comment]
Yip, I ended up doing just that - making the database format turned out to be a little too much like hard work ;)  I just pulled down the images, created the appopriate strings and it worked fine.  I now have no idea what I've done with the little script I made.

I'll close this issue and will open a PR if I do get round to it (that said, my itch has been scratched now ;) )
